graph TD
    Bernini[Gian Lorenzo Bernini]

    %% Escultores italianos
    GB[Giambologna]
    MA[Miguel Ángel]
    Donatello
    
    %% Escultores Franceses
    JS[Jacques Sarrazin]
    PP[Pierre Puget]
    FG[François Girardon]
    PL[Pierre Legros el Joven]

%% Relaciones
    Donatello -- "Iconografía de David" --> Bernini
    MA -- "Iconografía de David" --> Bernini
    GB -- "Influye en el primer" --> Bernini
    Bernini -- "Conocido por" --> JS
    Bernini -- "Influencia clara en" --> PP
    Bernini -- "Conoció a" --> FG
    Bernini -- "Seguidor de (en Roma)" --> PL